name = "Random123"
uuid = "74087812-796a-5b5d-8853-05524746bad3"
authors = ["Sunoru <s@sunoru.com>"]
version = "1.7.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"

[compat]
RandomNumbers = "1.4"
julia = "1.8"
